apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev-cluster
  namespace: istio-system
spec:
  acme:
    email: ranatunga@ex-offenders.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dev-cluster
    solvers:
    - http01:
        ingress:
          class: istio
